### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by 2mal3** [FlashyReese/ping-fabric#10]
The game crashes on startup.
Everything else is in the [crash log](https://github.com/FlashyReese/ping-fabric/files/5797164/crash-2021-01-11_17.53.36-client.txt).

**Comment by FlashyReese** [comment]
Quick question did you download the mod from Modrinth? and if so does the jar end with `-dev.jar`? It does look like you may be trying to load the `-dev.jar`

**Comment by 2mal3** [comment]
Yes, that was the problem. I have now downloaded the mod from curse forge, and it works fine.

**Comment by MightyKnight** [comment]
@FlashyReese Would you be able to remove the `-dev` version from Modrinth featured versions and add the real 1.2.1?
Since this **will** confuse more people.

I was just about to file another issue when I found this. :smile:
Thanks


**EDIT:** I just found out that you have the normal version present on Modrinth. However when clicking download on the main version page, Modrinth automatically serves the `-dev.jar`.
Is this a bug with Modrinth or can you configure it differently?
